apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn
# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: longhorn
# provisioner: driver.longhorn.io
# allowVolumeExpansion: true
# #volumeBindingMode: WaitForFirstConsumer
